In [1]:
# importing the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# loading the dataset 
dataset = pd.read_csv('StudentsPerformance.csv')
X = dataset.iloc[: , :-1].values  #the independent variables
y = dataset.iloc[: ,-1].values   # the dependent variables

In [3]:
# printing the data independent variables
print(X)

[['female' 'group B' "bachelor's degree" ... 'none' 72 72]
 ['female' 'group C' 'some college' ... 'completed' 69 90]
 ['female' 'group B' "master's degree" ... 'none' 90 95]
 ...
 ['female' 'group C' 'high school' ... 'completed' 59 71]
 ['female' 'group D' 'some college' ... 'completed' 68 78]
 ['female' 'group D' 'some college' ... 'none' 77 86]]


In [4]:
# encoding the data in our dataset there are various column whcih contains the categorical data 
# and our model needs it in the numerical form so fro that we use the onehot encoding methid

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0,1,2,3,4])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [5]:
print(X)

[[1.0 0.0 0.0 ... 1.0 72 72]
 [1.0 0.0 0.0 ... 0.0 69 90]
 [1.0 0.0 0.0 ... 1.0 90 95]
 ...
 [1.0 0.0 0.0 ... 0.0 59 71]
 [1.0 0.0 0.0 ... 0.0 68 78]
 [1.0 0.0 0.0 ... 1.0 77 86]]


In [6]:
# spliting the data into training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [7]:
# training the dataset on the basis of multiple linear regression
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [8]:
# predicting the results 
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)  #it will give the exactly two numbers after the decimal point
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_pred),1)),1))
# this will print the prediction in first column and then the real data


[[ 72.94  74.  ]
 [ 72.3   72.  ]
 [ 43.52  50.  ]
 [ 64.13  64.  ]
 [ 76.54  76.  ]
 [ 71.44  69.  ]
 [ 71.45  75.  ]
 [ 41.02  42.  ]
 [ 87.53  81.  ]
 [ 35.7   36.  ]
 [ 53.27  52.  ]
 [ 65.47  70.  ]
 [ 84.15  79.  ]
 [ 75.9   80.  ]
 [ 59.56  58.  ]
 [ 40.52  43.  ]
 [ 45.88  51.  ]
 [ 93.77  87.  ]
 [ 56.44  58.  ]
 [ 78.75  81.  ]
 [ 66.11  61.  ]
 [ 60.31  56.  ]
 [ 75.74  80.  ]
 [ 58.78  57.  ]
 [ 48.38  44.  ]
 [ 61.34  61.  ]
 [ 53.33  57.  ]
 [ 48.34  47.  ]
 [ 65.99  64.  ]
 [ 87.94  88.  ]
 [ 80.46  82.  ]
 [ 85.54  90.  ]
 [ 89.52  93.  ]
 [ 57.97  60.  ]
 [ 61.85  56.  ]
 [ 77.81  84.  ]
 [100.28 100.  ]
 [ 60.34  53.  ]
 [ 75.77  80.  ]
 [ 72.74  77.  ]
 [ 65.27  66.  ]
 [ 52.06  55.  ]
 [ 66.8   64.  ]
 [ 77.84  79.  ]
 [ 81.49  83.  ]
 [ 63.07  62.  ]
 [ 85.16  88.  ]
 [ 63.27  64.  ]
 [ 88.4   91.  ]
 [ 60.23  62.  ]
 [ 37.63  35.  ]
 [ 58.67  60.  ]
 [ 49.16  51.  ]
 [ 52.59  55.  ]
 [ 44.82  38.  ]
 [ 73.87  78.  ]
 [ 55.02  58.  ]
 [ 62.08  61.  ]
 [ 72.48  76. 